import type { Question } from '@/components/quiz/dataset'

export type { Question }

export const consonantQuestions: Question[] = [
	{ prompt: 'ก', answer: 'k', hint: 'no head (vs ถ ภ)' },
	{ prompt: 'ข', answer: 'kh', hint: 'crown (vs บ), no tail (vs ช), no serration (vs ฃ) · same translit as ฃ ฆ' },
	{ prompt: 'ฃ', answer: 'kh', hint: 'serrated crown (vs ข บ), no tail (vs ซ), no mid loop (vs ฆ) · same translit as ข ฆ' },
	{ prompt: 'ค', answer: 'kh', hint: 'head to right (vs ด), no tail (vs ศ), no serration (vs ต) · same translit as ฅ' },
	{ prompt: 'ฅ', answer: 'kh', hint: 'head to right (vs ต), serrated top (vs ค) · same translit as ค' },
	{ prompt: 'ฆ', answer: 'kh', hint: 'mid loop (vs ข), serrated crown (vs ม)' },
	{ prompt: 'ง', answer: 'ng'},
	{ prompt: 'จ', answer: 'ch', hint: 'head to left (vs อ), no mid loop (vs ฉ) · same translit as ฉ' },
	{ prompt: 'ฉ', answer: 'ch', hint: 'mid loop (vs จ) · same translit as จ' },
	{ prompt: 'ช', answer: 'ch', hint: 'tail (vs ข), no serration (vs ซ)' },
	{ prompt: 'ซ', answer: 's', hint: 'serrated crown (vs ช), tail (vs ฃ)' },
	{ prompt: 'ฌ', answer: 'ch', hint: 'mid loop in mid (vs ณ), no serration (vs ฒ)' },
	{ prompt: 'ญ', answer: 'y', hint: 'pedestal (vs ณ ฌ)' },
	{ prompt: 'ฎ', answer: 'd', hint: 'pedestal (vs ภ), no serration (vs ฏ)' },
	{ prompt: 'ฏ', answer: 't', hint: 'serrated pedestal (vs ฎ ภ)' },
	{ prompt: 'ฐ', answer: 'th', hint: 'pedestal (vs ธ จ), tail (vs จ), loop (vs ธ) · same translit as ธ' },
	{ prompt: 'ฑ', answer: 'th', hint: 'serrated crown (vs ท) · same translit as ท' },
	{ prompt: 'ฒ', answer: 'th', hint: 'serrated top (vs ฌ)' },
	{ prompt: 'ณ', answer: 'n', hint: 'mid loop on right (vs ฌ)' },
	{ prompt: 'ด', answer: 'd', hint: 'head to left (vs ค), no serration (vs ต)' },
	{ prompt: 'ต', answer: 't', hint: 'head to right (vs ค), serrated top (vs ด)' },
	{ prompt: 'ถ', answer: 'th', hint: 'head to right (vs ภ ก)' },
	{ prompt: 'ท', answer: 'th', hint: 'no mid loop (vs ห), no crown or serration (vs ฑ) · same translit as ฑ' },
	{ prompt: 'ธ', answer: 'th', hint: 'no head (vs ร), no pedestal (vs ฐ) · same translit as ฐ' },
	{ prompt: 'น', answer: 'n', hint: 'mid loop on right (vs ม บ)' },
	{ prompt: 'บ', answer: 'b', hint: 'no mid loop (vs ม น), no tail (vs ป ษ)' },
	{ prompt: 'ป', answer: 'p', hint: 'ascender tail (vs บ)' },
	{ prompt: 'ผ', answer: 'ph', hint: 'no tail (vs ฝ), head to right (vs พ) · same translit as พ' },
	{ prompt: 'ฝ', answer: 'f', hint: 'ascender tail (vs ผ), head to right (vs ฟ) · same translit as ฟ' },
	{ prompt: 'พ', answer: 'ph', hint: 'no tail (vs ฟ), head to left (vs ผ) · same translit as ผ' },
	{ prompt: 'ฟ', answer: 'f', hint: 'ascender tail (vs พ), head to left (vs ฝ) · same translit as ฝ' },
	{ prompt: 'ภ', answer: 'ph', hint: 'head to left (vs ก ถ)' },
	{ prompt: 'ม', answer: 'm', hint: 'mid loop on left (vs น บ), no serrated crown (vs ฆ)' },
	{ prompt: 'ย', answer: 'y', hint: 'beak (vs บ)' },
	{ prompt: 'ร', answer: 'r', hint: 'simple bottom (vs ธ)' },
	{ prompt: 'ล', answer: 'l', hint: 'no tail (vs ส)' },
	{ prompt: 'ว', answer: 'w' },
	{ prompt: 'ศ', answer: 's', hint: 'tail (vs ค)' },
	{ prompt: 'ษ', answer: 's', hint: 'mid-right tail (vs บ)' },
	{ prompt: 'ส', answer: 's', hint: 'tail (vs ล)' },
	{ prompt: 'ห', answer: 'h', hint: 'mid loop (vs ท)' },
	{ prompt: 'ฬ', answer: 'l', hint: 'loopy tail (vs พ ฟ)' },
	{ prompt: 'อ', answer: ['o', '-', ''], hint: 'no tail (vs ฮ), head on right (vs จ)' },
	{ prompt: 'ฮ', answer: 'h', hint: 'loopy tail (vs อ)' },
]

// ก is used as the base consonant throughout so focus stays on the vowel shape
export const vowelQuestions: Question[] = [
	{ prompt: 'กะ', answer: 'ka', hint: 'short a, open syllable' },
	{ prompt: 'กั', answer: 'ka', hint: 'short a, closed syllable' },
	{ prompt: 'กา', answer: 'ka', hint: 'long a' },
	{ prompt: 'กิ', answer: 'ki', hint: 'short i' },
	{ prompt: 'กี', answer: 'ki', hint: 'long i' },
	{ prompt: 'กุ', answer: 'ku', hint: 'short u' },
	{ prompt: 'กู', answer: 'ku', hint: 'long u' },
	{ prompt: 'กึ', answer: 'kue', hint: 'short ue' },
	{ prompt: 'กือ', answer: 'kue', hint: 'long ue, open syllable' },
	{ prompt: 'เก', answer: 'ke', hint: 'long e' },
	{ prompt: 'แก', answer: 'kae', hint: 'long ae' },
	{ prompt: 'โก', answer: 'ko', hint: 'long o' },
	{ prompt: 'กอ', answer: 'ko', hint: 'long open o' },
	{ prompt: 'เกาะ', answer: 'ko', hint: 'short open o, open syllable' },
	{ prompt: 'เกอ', answer: 'koe', hint: 'long oe, open syllable' },
	{ prompt: 'เกิ', answer: 'koe', hint: 'short oe, closed syllable' },
	{ prompt: 'เกีย', answer: 'kia', hint: 'diphthong ia' },
	{ prompt: 'กัว', answer: 'kua', hint: 'diphthong ua — ว acts as second element' },
	{ prompt: 'เกือ', answer: 'kuea', hint: 'triphthong uea — common in place names' },
	{ prompt: 'กำ', answer: 'kam', hint: '◌ํ + า; implied final m' },
	{ prompt: 'กรร', answer: 'ka', hint: 'ro han — รร reads as short a before a final consonant' },
]

export const syllableQuestions: Question[] = [
	{ prompt: 'นา', answer: 'na', hint: 'n + long a' },
	{ prompt: 'ดิน', answer: 'din', hint: 'd + short i + n' },
	{ prompt: 'มาก', answer: 'mak', hint: 'm + long a + k' },
	{ prompt: 'เป็น', answer: 'pen', hint: 'p + short e (เ◌็ before final) + n — "to be / can"' },
	{ prompt: 'แขน', answer: 'khaen', hint: 'kh + ae + n' },
	{ prompt: 'ดาว', answer: 'dao', hint: 'd + long a + w (becomes vowel glide ao)' },
	{ prompt: 'เขา', answer: 'khao', hint: 'mountain — kh + ao' },
	{ prompt: 'บาง', answer: 'bang', hint: 'waterway — b + long a + ng' },
	{ prompt: 'แม่', answer: 'mae', hint: 'river/mother — m + ae, mai ek tone mark' },
	{ prompt: 'เมือง', answer: 'mueang', hint: 'city/town — very common in place names' },
	{ prompt: 'เชียง', answer: 'chiang', hint: 'northern city prefix — ch + ia + ng' },
	{ prompt: 'กรุง', answer: 'krung', hint: 'cluster kr + u + ng — as in Krung Thep' },
	{ prompt: 'เทพ', answer: 'thep', hint: 'th + e + p — divine being' },
	{ prompt: 'ขอน', answer: 'khon', hint: 'kh + explicit sara o (อ) + n' },
	{ prompt: 'นคร', answer: 'nakhon', hint: 'great city — n + a + kh + o + n (final ร → n)' },
	{ prompt: 'บุรี', answer: 'buri', hint: 'city (Sanskrit) — b + u + r + ii' },
	{ prompt: 'ธานี', answer: 'thani', hint: 'city — th + aa + n + ii' },
	{ prompt: 'ราช', answer: ['rat', 'ratcha'], hint: 'royal — ร + า + ช (final ch → t)' },
	{ prompt: 'ศรี', answer: 'si', hint: 'auspicious — ร is silent in this Sanskrit cluster' },
	{ prompt: 'สอง', answer: 'song', hint: 'two — s + o + ng' },
	{ prompt: 'แก่น', answer: 'kaen', hint: 'core/essence — k + ae + n, mai ek tone mark' },
	{ prompt: 'หนอง', answer: 'nong', hint: 'swamp/pond — silent ห raises tone; n + inherent o + ng' },
	{ prompt: 'ป่า', answer: 'pa', hint: 'forest — p + long a, mai ek tone mark' },
	{ prompt: 'ลำ', answer: 'lam', hint: 'waterway — l + sara am (implied m)' },
	{ prompt: 'คลอง', answer: 'khlong', hint: 'canal — khl cluster + open o + ng' },
	{ prompt: 'น้ำ', answer: 'nam', hint: 'water — n + sara am, mai tho tone mark' },
	{ prompt: 'หาด', answer: 'hat', hint: 'beach — h + long a + d (final t)' },
	{ prompt: 'ใหม่', answer: 'mai', hint: 'new — ใ (rare ai spelling) +  silent ห raises tone + m + mai ek tone mark' },
	{ prompt: 'พรรณ', answer: 'phan', hint: 'ro han (รร) + final ณ — short a, final n' },
	{ prompt: 'กรรม', answer: 'kam', hint: 'ro han (รร) + final ม — short a, final m' },
	{ prompt: 'จังหวัด', answer: 'changwat', hint: 'province — จัง (chang) + หวัด (wat, silent ห raises ว class)' },
	{ prompt: 'อำเภอ', answer: 'amphoe', hint: 'district — อำ (am) + เภอ (phoe)' },
	{ prompt: 'เขต', answer: 'khet', hint: 'zone/district — used in Bangkok instead of อำเภอ' },
	{ prompt: 'ตำบล', answer: 'tambon', hint: 'sub-district — ตำ (tam) + บล (bon)' },
]

// All vowels — short + long pairs, inherent ai forms, and diphthongs
export const allVowelQuestions: Question[] = [
	// Short pure vowels
	{ prompt: 'กะ', answer: 'ka', hint: 'short a, open syllable' },
	{ prompt: 'กั', answer: 'ka', hint: 'short a, closed syllable' },
	{ prompt: 'กิ', answer: 'ki', hint: 'short i' },
	{ prompt: 'กุ', answer: 'ku', hint: 'short u' },
	{ prompt: 'กึ', answer: 'kue', hint: 'short ue' },
	{ prompt: 'เกะ', answer: 'ke', hint: 'short e, open syllable' },
	{ prompt: 'เก็', answer: 'ke', hint: 'short e, closed syllable' },
	{ prompt: 'แกะ', answer: 'kae', hint: 'short ae, open syllable' },
	{ prompt: 'แก็', answer: 'kae', hint: 'short ae, closed syllable' },
	{ prompt: 'โกะ', answer: 'ko', hint: 'short o, open syllable' },
	{ prompt: 'เกาะ', answer: 'ko', hint: 'short o, open syllable' },
	{ prompt: 'ก็อ', answer: 'ko', hint: 'short o, closed syllable' },
	{ prompt: 'เกอะ', answer: 'koe', hint: 'short oe, open syllable' },
	// Long pure vowels
	{ prompt: 'กา', answer: 'ka', hint: 'long a' },
	{ prompt: 'กี', answer: 'ki', hint: 'long i' },
	{ prompt: 'กู', answer: 'ku', hint: 'long u' },
	{ prompt: 'กือ', answer: 'kue', hint: 'long ue, open syllable' },
	{ prompt: 'กื', answer: 'kue', hint: 'long ue, closed syllable' },
	{ prompt: 'เก', answer: 'ke', hint: 'long e' },
	{ prompt: 'แก', answer: 'kae', hint: 'long ae' },
	{ prompt: 'โก', answer: 'ko', hint: 'long o' },
	{ prompt: 'กอ', answer: 'ko', hint: 'long o' },
	{ prompt: 'เกอ', answer: 'koe', hint: 'long oe — long schwa-like vowel, before + after' },
	{ prompt: 'เกิ', answer: 'koe', hint: 'sara oe short — เ◌ิ before a final consonant; e.g. เดิน doen' },
	// Inherent ai (two spellings, same sound)
	{ prompt: 'ไก', answer: 'kai', hint: 'mai malai — one of two spellings of ai; more common' },
	{ prompt: 'ใก', answer: 'kai', hint: 'mai malai noi — rarer ai spelling; only 20 words' },
	// Diphthongs with glide consonants
	{ prompt: 'เกา', answer: 'kao', hint: 'ao — เ◌า; ว acts as o-glide' },
	{ prompt: 'กาย', answer: 'kai', hint: 'ai — sara aa + ย as glide' },
	{ prompt: 'กาว', answer: 'kao', hint: 'ao — sara aa + ว as glide' },
	{ prompt: 'กิว', answer: 'kio', hint: 'io — sara i + ว as glide' },
	{ prompt: 'กอย', answer: 'koi', hint: 'oi — sara oo + ย as glide' },
	{ prompt: 'เกย', answer: 'koei', hint: 'oei — sara oe + ย as glide' },
	{ prompt: 'กุย', answer: 'kui', hint: 'ui — sara u + ย as glide' },
	// ia / ua / uea — long
	{ prompt: 'เกีย', answer: 'kia', hint: 'long ia' },
	{ prompt: 'กัว', answer: 'kua', hint: 'long ua' },
	{ prompt: 'เกือ', answer: 'kuea', hint: 'long uea triphthong' },
	// ia / ua / uea — short (rare in practice)
	{ prompt: 'เกียะ', answer: 'kia', hint: 'short ia — long form far more common' },
	{ prompt: 'กัวะ', answer: 'kua', hint: 'short ua — long form far more common' },
	{ prompt: 'เกือะ', answer: 'kuea', hint: 'short uea — long form far more common' },
	// Special compound vowels
	{ prompt: 'กำ', answer: 'kam', hint: 'sara am — ◌ํ + า; implied final m' },
	{ prompt: 'กรร', answer: 'ka', hint: 'ro han — รร reads as short a before a final consonant' },
]

// All 77 Thai provinces (76 provinces + Bangkok)
export const provinceQuestions: Question[] = [
	{ prompt: 'กระบี่', answer: 'Krabi' },
	{ prompt: 'กาญจนบุรี', answer: 'Kanchanaburi' },
	{ prompt: 'กาฬสินธุ์', answer: 'Kalasin', hint: 'ฬ = l; ธุ์ is silent' },
	{ prompt: 'กำแพงเพชร', answer: 'Kamphaeng Phet', hint: 'เพชร → phet: ชร cluster, ช final = t, ร silent' },
	{ prompt: 'กรุงเทพมหานคร', answer: ['Krung Thep Maha Nakhnon', 'Krung Thep', 'Bangkok'] },
	{ prompt: 'ขอนแก่น', answer: 'Khon Kaen' },
	{ prompt: 'จันทบุรี', answer: 'Chanthaburi' },
	{ prompt: 'ฉะเชิงเทรา', answer: 'Chachoengsao', hint: 'highly irregular romanisation' },
	{ prompt: 'ชลบุรี', answer: 'Chon Buri', hint: 'ล final = n → Chon (not Chol)' },
	{ prompt: 'ชัยนาท', answer: 'Chai Nat', hint: 'ท final = t → Nat' },
	{ prompt: 'ชัยภูมิ', answer: 'Chaiyaphum', hint: 'ภูมิ → phum: trailing short -i vowel dropped in romanisation' },
	{ prompt: 'ชุมพร', answer: 'Chumphon', hint: 'ร final = n → Chumphon' },
	{ prompt: 'เชียงราย', answer: 'Chiang Rai' },
	{ prompt: 'เชียงใหม่', answer: 'Chiang Mai', hint: 'ใ is the rarer ai spelling (~20 words use ใ vs ไ)' },
	{ prompt: 'ตรัง', answer: 'Trang' },
	{ prompt: 'ตราด', answer: 'Trat', hint: 'ด final = t' },
	{ prompt: 'ตาก', answer: 'Tak' },
	{ prompt: 'นครนายก', answer: 'Nakhon Nayok', hint: 'นคร: ร final = n → Nakhon' },
	{ prompt: 'นครปฐม', answer: 'Nakhon Pathom', hint: 'ฐ = th (rare letter); ปฐม → Pathom' },
	{ prompt: 'นครพนม', answer: 'Nakhon Phanom' },
	{ prompt: 'นครราชสีมา', answer: ['Nakhon Ratchasima', 'Korat'], hint: 'ราช: ช final = t → ratch' },
	{ prompt: 'นครศรีธรรมราช', answer: 'Nakhon Si Thammarat', hint: 'ร silent in ศร → Si; รร = short a → Thamm; ช final = t → rat' },
	{ prompt: 'นครสวรรค์', answer: 'Nakhon Sawan', hint: 'ค์ silent → Sawan (not Sawank)' },
	{ prompt: 'นนทบุรี', answer: 'Nonthaburi' },
	{ prompt: 'นราธิวาส', answer: 'Narathiwat', hint: 'ส final = t → wat' },
	{ prompt: 'น่าน', answer: 'Nan' },
	{ prompt: 'บึงกาฬ', answer: 'Bueng Kan', hint: 'ฬ rare letter (= l initially); as final = n → Kan' },
	{ prompt: 'บุรีรัมย์', answer: ['Buri Ram', 'Buriram'], hint: 'ย์ silent → Ram' },
	{ prompt: 'ปทุมธานี', answer: 'Pathum Thani' },
	{ prompt: 'ประจวบคีรีขันธ์', answer: 'Prachuap Khiri Khan', hint: 'ธ์ silent → Khan' },
	{ prompt: 'ปราจีนบุรี', answer: 'Prachin Buri' },
	{ prompt: 'ปัตตานี', answer: 'Pattani' },
	{ prompt: 'พระนครศรีอยุธยา', answer: ['Phra Nakhon Si Ayutthaya', 'Ayutthaya'], hint: 'ร silent in ศร → Si; อยุธยา: ธ = th → tthaya (doubled in official romanisation)' },
	{ prompt: 'พะเยา', answer: 'Phayao' },
	{ prompt: 'พังงา', answer: 'Phang Nga' },
	{ prompt: 'พัทลุง', answer: 'Phatthalung', hint: 'พัท: ท final = t → phat; official romanisation doubles the t' },
	{ prompt: 'พิจิตร', answer: 'Phichit', hint: 'จิตร: ตร cluster, ร silent → chit' },
	{ prompt: 'พิษณุโลก', answer: 'Phitsanulok', hint: 'ษ = s (rare letter, same sound as ส/ซ)' },
	{ prompt: 'เพชรบุรี', answer: 'Phetchaburi', hint: 'เพชร → phet: ชร cluster, ช final = t, ร silent' },
	{ prompt: 'เพชรบูรณ์', answer: 'Phetchabun', hint: 'ณ์ silent → Phetchabun' },
	{ prompt: 'แพร่', answer: 'Phrae', hint: 'phr- open syllable (ร is part of onset cluster, not a final)' },
	{ prompt: 'ภูเก็ต', answer: ['Phuket', 'Phu Ket'], hint: 'เ◌็ = short e (mai taikhu); ต final = t' },
	{ prompt: 'มหาสารคาม', answer: 'Maha Sarakham', hint: 'สาร → "sara": ร treated as onset of next syllable, not final n' },
	{ prompt: 'มุกดาหาร', answer: 'Mukdahan', hint: 'ร final = n → Mukdahan (not Mukdahar)' },
	{ prompt: 'แม่ฮ่องสอน', answer: 'Mae Hong Son', hint: 'ฮ = h (lower-class h, less common than ห)' },
	{ prompt: 'ยโสธร', answer: 'Yasothon', hint: 'ร final = n → Yasothon' },
	{ prompt: 'ยะลา', answer: 'Yala' },
	{ prompt: 'ร้อยเอ็ด', answer: 'Roi Et', hint: 'เ◌็ = short e; ด final = t → Et' },
	{ prompt: 'ระนอง', answer: 'Ranong' },
	{ prompt: 'ระยอง', answer: 'Rayong' },
	{ prompt: 'ราชบุรี', answer: 'Ratchaburi', hint: 'ราช: ช final = t → Ratch' },
	{ prompt: 'ลพบุรี', answer: 'Lop Buri', hint: 'พ final = p → Lop' },
	{ prompt: 'ลำปาง', answer: 'Lampang', hint: 'ลำ = lam (sara am, implied m)' },
	{ prompt: 'ลำพูน', answer: 'Lamphun', hint: 'ลำ = lam (sara am); ภ = ph' },
	{ prompt: 'เลย', answer: 'Loei', hint: 'เ◌ย = oei diphthong → Loei (not "Ley")' },
	{ prompt: 'ศรีสะเกษ', answer: ['Si Sa Ket', 'Sisaket'], hint: 'ร silent in ศร → Si; ษ final = t → Ket' },
	{ prompt: 'สกลนคร', answer: 'Sakon Nakhon', hint: 'ล final = n → Sakon' },
	{ prompt: 'สงขลา', answer: 'Songkhla', hint: 'khl- cluster → Songkhla' },
	{ prompt: 'สตูล', answer: 'Satun', hint: 'ล final = n → Satun' },
	{ prompt: 'สมุทรปราการ', answer: 'Samut Prakan', hint: 'สมุทร: ทร cluster, ร silent → Samut' },
	{ prompt: 'สมุทรสงคราม', answer: 'Samut Songkhram', hint: 'สมุทร: ทร cluster, ร silent → Samut' },
	{ prompt: 'สมุทรสาคร', answer: 'Samut Sakhon', hint: 'สมุทร: ทร, ร silent → Samut; สาคร: คร cluster, ร final = n → Sakhon' },
	{ prompt: 'สระแก้ว', answer: 'Sa Kaeo', hint: 'สระ compressed to "sa" in romanisation' },
	{ prompt: 'สระบุรี', answer: 'Saraburi', hint: 'สระ romanised as "sara" here — same word as in สระแก้ว, different official form' },
	{ prompt: 'สิงห์บุรี', answer: 'Sing Buri', hint: 'ห์ silent → Sing' },
	{ prompt: 'สุโขทัย', answer: 'Sukhothai', hint: 'ทัย = thai (ท = th, ัย = ai diphthong)' },
	{ prompt: 'สุพรรณบุรี', answer: 'Suphan Buri', hint: 'พรรณ: รร = short a + ณ final = n → phan' },
	{ prompt: 'สุราษฎร์ธานี', answer: 'Surat Thani', hint: 'ราษฎร์: ฎร์ silent → rat' },
	{ prompt: 'สุรินทร์', answer: 'Surin', hint: 'ทร์ silent → Surin' },
	{ prompt: 'หนองคาย', answer: 'Nong Khai', hint: 'คาย = khai (long a + ย glide = ai)' },
	{ prompt: 'หนองบัวลำภู', answer: 'Nong Bua Lam Phu', hint: 'บัว = bua (ua diphthong); ภ = ph' },
	{ prompt: 'อ่างทอง', answer: 'Ang Thong' },
	{ prompt: 'อำนาจเจริญ', answer: 'Amnat Charoen', hint: 'จ final = t → nat; เจริญ: ญ final = n → roen' },
	{ prompt: 'อุดรธานี', answer: 'Udon Thani', hint: 'ดร: ร final = n → Udon' },
	{ prompt: 'อุตรดิตถ์', answer: 'Uttaradit', hint: 'ถ์ silent; ตร cluster' },
	{ prompt: 'อุทัยธานี', answer: 'Uthai Thani', hint: 'ทัย = thai (ท = th, ัย = ai diphthong)' },
	{ prompt: 'อุบลราชธานี', answer: ['Ubon Ratchathani', 'Ubon'], hint: 'ล final = n → Ubon; ราช: ช final = t → ratch' },
]

const prefixed = (prefix: string, meaning: string, q: Question): Question => ({
	prompt: prefix + q.prompt,
	answer: q.answer,
	hint: [prefix + ' = ' + meaning, q.hint].filter(Boolean).join(' · '),
})

const nonBangkok = provinceQuestions.filter(q => q.prompt !== 'กรุงเทพมหานคร')

// จังหวัด / จ. (province) + all 77; อำเภอเมือง / อ.เมือง (central district) + all except Bangkok (uses เขต)
export const provincePrefixQuestions: Question[] = [
	...provinceQuestions.map(q => prefixed('จังหวัด', 'province', q)),
	...provinceQuestions.map(q => prefixed('จ.', 'province (abbr.)', q)),
	...nonBangkok.map(q => prefixed('อำเภอเมือง', 'central district of', q)),
	...nonBangkok.map(q => prefixed('อ.เมือง', 'central district (abbr.)', q)),
]
