import type { Question } from '@/components/quiz/dataset'

export type { Question }

export const consonantQuestions: Question[] = [
	{ prompt: 'ก', answer: 'k',    hint: 'ko kai · mid class' },
	{ prompt: 'ข', answer: 'kh',   hint: 'kho khai · high class' },
	{ prompt: 'ฃ', answer: 'kh',   hint: 'kho khuat · high class · obsolete' },
	{ prompt: 'ค', answer: 'kh',   hint: 'kho khwai · low class' },
	{ prompt: 'ฅ', answer: 'kh',   hint: 'kho khon · low class · obsolete' },
	{ prompt: 'ฆ', answer: 'kh',   hint: 'kho rakhang · low class' },
	{ prompt: 'ง', answer: 'ng',   hint: 'ngo ngu · low class · also final ng' },
	{ prompt: 'จ', answer: 'ch',   hint: 'cho chan · mid class · final t' },
	{ prompt: 'ฉ', answer: 'ch',   hint: 'cho ching · high class · no final' },
	{ prompt: 'ช', answer: 'ch',   hint: 'cho chang · low class · final t' },
	{ prompt: 'ซ', answer: 's',    hint: 'so so · low class · final t' },
	{ prompt: 'ฌ', answer: 'ch',   hint: 'cho choe · low class · rare' },
	{ prompt: 'ญ', answer: 'y',    hint: 'yo ying · low class · final n' },
	{ prompt: 'ฎ', answer: 'd',    hint: 'do chada · mid class · rare · final t' },
	{ prompt: 'ฏ', answer: 't',    hint: 'to patak · mid class · rare · final t' },
	{ prompt: 'ฐ', answer: 'th',   hint: 'tho than · high class · final t' },
	{ prompt: 'ฑ', answer: 'th',   hint: 'tho nangmontho · low class · final t' },
	{ prompt: 'ฒ', answer: 'th',   hint: 'tho phuthao · low class · final t' },
	{ prompt: 'ณ', answer: 'n',    hint: 'no nen · low class · also final n' },
	{ prompt: 'ด', answer: 'd',    hint: 'do dek · mid class · final t' },
	{ prompt: 'ต', answer: 't',    hint: 'to tao · mid class · final t' },
	{ prompt: 'ถ', answer: 'th',   hint: 'tho thung · high class · final t' },
	{ prompt: 'ท', answer: 'th',   hint: 'tho thahan · low class · final t' },
	{ prompt: 'ธ', answer: 'th',   hint: 'tho thong · low class · final t' },
	{ prompt: 'น', answer: 'n',    hint: 'no nu · low class · also final n' },
	{ prompt: 'บ', answer: 'b',    hint: 'bo baimai · mid class · final p' },
	{ prompt: 'ป', answer: 'p',    hint: 'po pla · mid class · final p' },
	{ prompt: 'ผ', answer: 'ph',   hint: 'pho phueng · high class · no final' },
	{ prompt: 'ฝ', answer: 'f',    hint: 'fo fa · high class · no final' },
	{ prompt: 'พ', answer: 'ph',   hint: 'pho phan · low class · final p' },
	{ prompt: 'ฟ', answer: 'f',    hint: 'fo fan · low class · final p' },
	{ prompt: 'ภ', answer: 'ph',   hint: 'pho samphao · low class · final p' },
	{ prompt: 'ม', answer: 'm',    hint: 'mo ma · low class · also final m' },
	{ prompt: 'ย', answer: 'y',    hint: 'yo yak · low class · final y' },
	{ prompt: 'ร', answer: 'r',    hint: 'ro ruea · low class · final n or silent' },
	{ prompt: 'ล', answer: 'l',    hint: 'lo ling · low class · final n' },
	{ prompt: 'ว', answer: 'w',    hint: 'wo waen · low class · final o/u (vowel glide)' },
	{ prompt: 'ศ', answer: 's',    hint: 'so sala · high class · final t' },
	{ prompt: 'ษ', answer: 's',    hint: 'so ruesi · high class · final t' },
	{ prompt: 'ส', answer: 's',    hint: 'so suea · high class · final t' },
	{ prompt: 'ห', answer: 'h',    hint: 'ho hip · high class · no final' },
	{ prompt: 'ฬ', answer: 'l',    hint: 'lo chula · low class · final n · rare' },
	{ prompt: 'อ', answer: ['–', '-', ''], hint: 'o ang · mid class · silent vowel carrier / glottal' },
	{ prompt: 'ฮ', answer: 'h',    hint: 'ho nokhuk · low class · no final' },
]

// ก is used as the base consonant throughout so focus stays on the vowel shape
export const vowelQuestions: Question[] = [
	{ prompt: 'กา',   answer: 'ka',   hint: 'sara aa — long a, written after consonant' },
	{ prompt: 'กะ',   answer: 'ka',   hint: 'sara a — short a, open syllable' },
	{ prompt: 'กิ',   answer: 'ki',   hint: 'sara i — short i, written above' },
	{ prompt: 'กี',   answer: 'ki',   hint: 'sara ii — long i, written above' },
	{ prompt: 'กึ',   answer: 'kue',  hint: 'sara ue — short ue, written above' },
	{ prompt: 'กือ',  answer: 'kue',  hint: 'sara uue — long ue, above + after' },
	{ prompt: 'กุ',   answer: 'ku',   hint: 'sara u — short u, written below' },
	{ prompt: 'กู',   answer: 'ku',   hint: 'sara uu — long u, written below' },
	{ prompt: 'เก',   answer: 'ke',   hint: 'sara e — long e, written before consonant' },
	{ prompt: 'แก',   answer: 'kae',  hint: 'sara ae — long ae (as in cat), written before' },
	{ prompt: 'โก',   answer: 'ko',   hint: 'sara o — long o, written before' },
	{ prompt: 'กอ',   answer: 'ko',   hint: 'sara oo — long open o (as in or), written after' },
	{ prompt: 'เกาะ', answer: 'ko',   hint: 'short open o — เ◌าะ wraps the consonant' },
	{ prompt: 'เกอ',  answer: 'koe',  hint: 'sara oe — long schwa-like vowel, before + after' },
	{ prompt: 'เกีย', answer: 'kia',  hint: 'diphthong ia — before + above + after' },
	{ prompt: 'กัว',  answer: 'kua',  hint: 'diphthong ua — ว acts as second element' },
	{ prompt: 'เกือ', answer: 'kuea', hint: 'triphthong uea — common in place names' },
]

export const syllableQuestions: Question[] = [
	{ prompt: 'นา',    answer: 'na',     hint: 'n + long a' },
	{ prompt: 'ดิน',   answer: 'din',    hint: 'd + short i + n' },
	{ prompt: 'มาก',   answer: 'mak',    hint: 'm + long a + k' },
	{ prompt: 'เกน',   answer: 'ken',    hint: 'k + long e + n' },
	{ prompt: 'แขน',   answer: 'khaen',  hint: 'kh + ae + n' },
	{ prompt: 'ดาว',   answer: 'dao',    hint: 'd + long a + w (becomes vowel glide ao)' },
	{ prompt: 'เขา',   answer: 'khao',   hint: 'mountain — kh + ao' },
	{ prompt: 'บาง',   answer: 'bang',   hint: 'waterway — b + long a + ng' },
	{ prompt: 'แม่',   answer: 'mae',    hint: 'river/mother — m + ae, mai ek tone mark' },
	{ prompt: 'เมือง', answer: 'mueang', hint: 'city/town — very common in place names' },
	{ prompt: 'เชียง', answer: 'chiang', hint: 'northern city prefix — ch + ia + ng' },
	{ prompt: 'กรุง',  answer: 'krung',  hint: 'cluster kr + u + ng — as in Krung Thep' },
	{ prompt: 'เทพ',   answer: 'thep',   hint: 'th + e + p — divine being' },
	{ prompt: 'ขอน',   answer: 'khon',   hint: 'kh + inherent o + n' },
	{ prompt: 'นคร',   answer: 'nakhon', hint: 'great city — n + a + kh + o + n (final ร → n)' },
	{ prompt: 'บุรี',  answer: 'buri',   hint: 'city (Sanskrit) — b + u + r + ii' },
	{ prompt: 'ธานี',  answer: 'thani',  hint: 'city — th + aa + n + ii' },
	{ prompt: 'ราช',   answer: ['rat', 'ratcha'], hint: 'royal — ร + า + ช (final ch → t)' },
	{ prompt: 'ศรี',   answer: 'si',     hint: 'auspicious — ร is silent in this Sanskrit cluster' },
	{ prompt: 'สอง',   answer: 'song',   hint: 'two — s + o + ng' },
	{ prompt: 'แก่น',  answer: 'kaen',   hint: 'core/essence — k + ae + n, mai ek tone mark' },
]

export const placeQuestions: Question[] = [
	{ prompt: 'ตาก', answer: 'Tak' },
	{ prompt: 'น่าน', answer: 'Nan' },
	{ prompt: 'ตรัง', answer: 'Trang' },
	{ prompt: 'แพร่', answer: 'Phrae' },
	{ prompt: 'พะเยา', answer: 'Phayao' },
	{ prompt: 'ระยอง', answer: 'Rayong' },
	{ prompt: 'เชียงใหม่', answer: 'Chiang Mai', hint: 'northern capital' },
	{ prompt: 'เชียงราย', answer: 'Chiang Rai' },
	{ prompt: 'ขอนแก่น', answer: 'Khon Kaen' },
	{ prompt: 'ชลบุรี', answer: 'Chon Buri' },
	{ prompt: 'ลพบุรี', answer: 'Lop Buri' },
	{ prompt: 'สุโขทัย', answer: ['Sukhothai', 'Sukho Thai'] },
	{ prompt: 'อยุธยา', answer: 'Ayutthaya', hint: 'former capital' },
	{ prompt: 'ปทุมธานี', answer: 'Pathum Thani' },
	{ prompt: 'นนทบุรี', answer: 'Nonthaburi' },
	{ prompt: 'กรุงเทพ', answer: ['Krung Thep', 'Bangkok'], hint: 'capital city' },
	{ prompt: 'ภูเก็ต', answer: ['Phuket', 'Phu Ket'], hint: 'island province' },
	{ prompt: 'นครราชสีมา', answer: ['Nakhon Ratchasima', 'Korat'], hint: 'also called Korat' },
	{ prompt: 'สุราษฎร์ธานี', answer: 'Surat Thani' },
	{ prompt: 'นครศรีธรรมราช', answer: 'Nakhon Si Thammarat' },
	{ prompt: 'อุบลราชธานี', answer: ['Ubon Ratchathani', 'Ubon'] },
	{ prompt: 'ประจวบคีรีขันธ์', answer: 'Prachuap Khiri Khan' },
	{ prompt: 'กาญจนบุรี', answer: 'Kanchanaburi' },
	{ prompt: 'นครสวรรค์', answer: 'Nakhon Sawan' },
	{ prompt: 'แม่ฮ่องสอน', answer: 'Mae Hong Son' },
	{ prompt: 'สมุทรปราการ', answer: 'Samut Prakan' },
]

// All vowels — short + long pairs, inherent ai forms, and diphthongs
export const allVowelQuestions: Question[] = [
	// Short pure vowels
	{ prompt: 'กะ',    answer: 'ka',   hint: 'sara a — short a, open syllable' },
	{ prompt: 'กิ',    answer: 'ki',   hint: 'sara i — short i, above consonant' },
	{ prompt: 'กึ',    answer: 'kue',  hint: 'sara ue — short ue, above consonant' },
	{ prompt: 'กุ',    answer: 'ku',   hint: 'sara u — short u, below consonant' },
	{ prompt: 'เกะ',   answer: 'ke',   hint: 'sara e — short e; เ◌็ before a final consonant' },
	{ prompt: 'แกะ',   answer: 'kae',  hint: 'sara ae — short ae, before consonant' },
	{ prompt: 'โกะ',   answer: 'ko',   hint: 'sara o — short high-mid o, before consonant' },
	{ prompt: 'เกาะ',  answer: 'ko',   hint: 'short open o — เ◌าะ wraps the consonant' },
	{ prompt: 'เกอะ',  answer: 'koe',  hint: 'short oe — rare; schwa-like quality' },
	// Long pure vowels
	{ prompt: 'กา',    answer: 'ka',   hint: 'sara aa — long a, after consonant' },
	{ prompt: 'กี',    answer: 'ki',   hint: 'sara ii — long i, above consonant' },
	{ prompt: 'กือ',   answer: 'kue',  hint: 'sara uue — long ue, above + after consonant' },
	{ prompt: 'กู',    answer: 'ku',   hint: 'sara uu — long u, below consonant' },
	{ prompt: 'เก',    answer: 'ke',   hint: 'sara e — long e, before consonant' },
	{ prompt: 'แก',    answer: 'kae',  hint: 'sara ae — long ae, before consonant' },
	{ prompt: 'โก',    answer: 'ko',   hint: 'sara o — long high-mid o, before consonant' },
	{ prompt: 'กอ',    answer: 'ko',   hint: 'sara oo — long open o (as in or), after consonant' },
	{ prompt: 'เกอ',   answer: 'koe',  hint: 'sara oe — long schwa-like vowel, before + after' },
	// Inherent ai (two spellings, same sound)
	{ prompt: 'ไก',    answer: 'kai',  hint: 'mai malai — one of two spellings of ai; more common' },
	{ prompt: 'ใก',    answer: 'kai',  hint: 'mai malai noi — rarer ai spelling; only 20 words' },
	// Diphthongs with glide consonants
	{ prompt: 'เกา',   answer: 'kao',  hint: 'ao — เ◌า; ว acts as o-glide' },
	{ prompt: 'กาย',   answer: 'kai',  hint: 'ai — sara aa + ย as glide' },
	{ prompt: 'กาว',   answer: 'kao',  hint: 'ao — sara aa + ว as glide' },
	{ prompt: 'กิว',   answer: 'kio',  hint: 'io — sara i + ว as glide' },
	{ prompt: 'กอย',   answer: 'koi',  hint: 'oi — sara oo + ย as glide' },
	{ prompt: 'เกย',   answer: 'koei', hint: 'oei — sara oe + ย as glide' },
	{ prompt: 'กุย',   answer: 'kui',  hint: 'ui — sara u + ย as glide' },
	// ia / ua / uea — long
	{ prompt: 'เกีย',  answer: 'kia',  hint: 'ia — before + above + after consonant; long form' },
	{ prompt: 'กัว',   answer: 'kua',  hint: 'ua — ว acts as second element; long form' },
	{ prompt: 'เกือ',  answer: 'kuea', hint: 'uea triphthong — long form; common in place names' },
	// ia / ua / uea — short (rare in practice)
	{ prompt: 'เกียะ', answer: 'kia',  hint: 'ia short — long form far more common' },
	{ prompt: 'กัวะ',  answer: 'kua',  hint: 'ua short — long form far more common' },
	{ prompt: 'เกือะ', answer: 'kuea', hint: 'uea short — long form far more common' },
]

// All 77 Thai provinces (76 provinces + Bangkok)
export const provinceQuestions: Question[] = [
	{ prompt: 'กระบี่',             answer: 'Krabi' },
	{ prompt: 'กาญจนบุรี',          answer: 'Kanchanaburi' },
	{ prompt: 'กาฬสินธุ์',          answer: 'Kalasin',         hint: 'ฬ = l; ธุ์ is silent' },
	{ prompt: 'กำแพงเพชร',          answer: 'Kamphaeng Phet' },
	{ prompt: 'กรุงเทพมหานคร',      answer: ['Bangkok', 'Krung Thep'], hint: 'capital — special administrative area' },
	{ prompt: 'ขอนแก่น',            answer: 'Khon Kaen' },
	{ prompt: 'จันทบุรี',           answer: 'Chanthaburi' },
	{ prompt: 'ฉะเชิงเทรา',         answer: 'Chachoengsao',    hint: 'highly irregular romanisation' },
	{ prompt: 'ชลบุรี',             answer: 'Chon Buri' },
	{ prompt: 'ชัยนาท',             answer: 'Chai Nat' },
	{ prompt: 'ชัยภูมิ',            answer: 'Chaiyaphum' },
	{ prompt: 'ชุมพร',              answer: 'Chumphon' },
	{ prompt: 'เชียงราย',           answer: 'Chiang Rai' },
	{ prompt: 'เชียงใหม่',          answer: 'Chiang Mai' },
	{ prompt: 'ตรัง',               answer: 'Trang' },
	{ prompt: 'ตราด',               answer: 'Trat' },
	{ prompt: 'ตาก',                answer: 'Tak' },
	{ prompt: 'นครนายก',            answer: 'Nakhon Nayok' },
	{ prompt: 'นครปฐม',             answer: 'Nakhon Pathom' },
	{ prompt: 'นครพนม',             answer: 'Nakhon Phanom' },
	{ prompt: 'นครราชสีมา',         answer: ['Nakhon Ratchasima', 'Korat'], hint: 'also known as Korat' },
	{ prompt: 'นครศรีธรรมราช',      answer: 'Nakhon Si Thammarat' },
	{ prompt: 'นครสวรรค์',          answer: 'Nakhon Sawan' },
	{ prompt: 'นนทบุรี',            answer: 'Nonthaburi' },
	{ prompt: 'นราธิวาส',           answer: 'Narathiwat' },
	{ prompt: 'น่าน',               answer: 'Nan' },
	{ prompt: 'บึงกาฬ',             answer: 'Bueng Kan',        hint: 'newest province, created 2011' },
	{ prompt: 'บุรีรัมย์',          answer: 'Buri Ram' },
	{ prompt: 'ปทุมธานี',           answer: 'Pathum Thani' },
	{ prompt: 'ประจวบคีรีขันธ์',    answer: 'Prachuap Khiri Khan' },
	{ prompt: 'ปราจีนบุรี',         answer: 'Prachin Buri' },
	{ prompt: 'ปัตตานี',            answer: 'Pattani' },
	{ prompt: 'พระนครศรีอยุธยา',    answer: ['Phra Nakhon Si Ayutthaya', 'Ayutthaya'], hint: 'former capital' },
	{ prompt: 'พะเยา',              answer: 'Phayao' },
	{ prompt: 'พังงา',              answer: 'Phang Nga' },
	{ prompt: 'พัทลุง',             answer: 'Phatthalung' },
	{ prompt: 'พิจิตร',             answer: 'Phichit' },
	{ prompt: 'พิษณุโลก',           answer: 'Phitsanulok' },
	{ prompt: 'เพชรบุรี',           answer: 'Phetchaburi' },
	{ prompt: 'เพชรบูรณ์',          answer: 'Phetchabun' },
	{ prompt: 'แพร่',               answer: 'Phrae' },
	{ prompt: 'ภูเก็ต',             answer: ['Phuket', 'Phu Ket'] },
	{ prompt: 'มหาสารคาม',          answer: 'Maha Sarakham' },
	{ prompt: 'มุกดาหาร',           answer: 'Mukdahan' },
	{ prompt: 'แม่ฮ่องสอน',         answer: 'Mae Hong Son' },
	{ prompt: 'ยโสธร',              answer: 'Yasothon' },
	{ prompt: 'ยะลา',               answer: 'Yala' },
	{ prompt: 'ร้อยเอ็ด',           answer: 'Roi Et' },
	{ prompt: 'ระนอง',              answer: 'Ranong' },
	{ prompt: 'ระยอง',              answer: 'Rayong' },
	{ prompt: 'ราชบุรี',            answer: 'Ratchaburi' },
	{ prompt: 'ลพบุรี',             answer: 'Lop Buri' },
	{ prompt: 'ลำปาง',              answer: 'Lampang' },
	{ prompt: 'ลำพูน',              answer: 'Lamphun' },
	{ prompt: 'เลย',                answer: 'Loei' },
	{ prompt: 'ศรีสะเกษ',           answer: 'Si Sa Ket' },
	{ prompt: 'สกลนคร',             answer: 'Sakon Nakhon' },
	{ prompt: 'สงขลา',              answer: 'Songkhla' },
	{ prompt: 'สตูล',               answer: 'Satun' },
	{ prompt: 'สมุทรปราการ',        answer: 'Samut Prakan' },
	{ prompt: 'สมุทรสงคราม',        answer: 'Samut Songkhram' },
	{ prompt: 'สมุทรสาคร',          answer: 'Samut Sakhon' },
	{ prompt: 'สระแก้ว',            answer: 'Sa Kaeo' },
	{ prompt: 'สระบุรี',            answer: 'Saraburi' },
	{ prompt: 'สิงห์บุรี',          answer: 'Sing Buri' },
	{ prompt: 'สุโขทัย',            answer: 'Sukhothai' },
	{ prompt: 'สุพรรณบุรี',         answer: 'Suphan Buri' },
	{ prompt: 'สุราษฎร์ธานี',       answer: 'Surat Thani' },
	{ prompt: 'สุรินทร์',           answer: 'Surin' },
	{ prompt: 'หนองคาย',            answer: 'Nong Khai' },
	{ prompt: 'หนองบัวลำภู',        answer: 'Nong Bua Lam Phu' },
	{ prompt: 'อ่างทอง',            answer: 'Ang Thong' },
	{ prompt: 'อำนาจเจริญ',         answer: 'Amnat Charoen' },
	{ prompt: 'อุดรธานี',           answer: 'Udon Thani' },
	{ prompt: 'อุตรดิตถ์',          answer: 'Uttaradit' },
	{ prompt: 'อุทัยธานี',          answer: 'Uthai Thani' },
	{ prompt: 'อุบลราชธานี',        answer: ['Ubon Ratchathani', 'Ubon'] },
]
